{% set name = "sasoptpy" %}

package:
  name: "{{ name }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_')|replace('v', '') }}"

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.15.4
    - pandas >=1.0.0
    - pip
    - python
    - saspy ==3.3.7
    - swat >=1.6.1
  run:
    - numpy >=1.15.4
    - pandas >=1.0.0
    - pip
    - python
    - saspy ==3.3.7
    - swat >=1.6.1

test:
  imports:
    - sasoptpy

about:
  home: https://github.com/sassoftware/sasoptpy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "SAS Optimization Interface for Python"
  doc_url: https://sassoftware.github.io/sasoptpy
  dev_url: https://github.com/sassoftware/sasoptpy

extra:
  recipe-maintainers:
    - "Sertalp B. Cay <sertalpbilal@gmail.com>"
