{% set name = "sasoptpy" %}

package:
  name: "{{ name }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_')|replace('v', '') }}"

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pandas
    - pip
    - python
    - saspy
    - swat
  run:
    - numpy
    - pandas
    - pip
    - python
    - saspy
    - swat

test:
  imports:
    - sasoptpy

about:
  home: https://github.com/sassoftware/sasoptpy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "SAS Optimization Interface for Python"
  doc_url: https://sassoftware.github.io/sasoptpy
  dev_url: https://github.com/sassoftware/sasoptpy

extra:
  recipe-maintainers:
    - "Sertalp B. Cay <sertalpbilal@gmail.com>"
